version: "3"

services:
  db:
    container_name: db-agape-dev
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: "mypassword"
    ports:
      - "5432:5432"

  # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
  pgadmin:
    image: dpage/pgadmin4:7.4
    container_name: pgadmin4-dev
    restart: always
    ports:
      - "8080:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@mapineda48.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    volumes:
      - ./.devcontainer/pgadmin4/server.json:/pgadmin4/servers.json
    depends_on:
      - db

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9090" /data
    ports:
      - 9000:9000
      - 9090:9090


