export const EVENT_UPDATE = Symbol("EVENT_FORM_PRODUCT_CREATE_OR_UPDATE");
export const EVENT_DELETE = Symbol("EVENT_FORM_PRODUCT_DELETE");
export const EVENT_CLOSE = Symbol("EVENT_FORM_PRODUCT_CLOSE");