export const products = [
  {
    image: "assets/img/shop_01.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 1,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_02.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 2,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_03.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 3,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_04.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 4,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_05.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 5,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_06.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 3,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_07.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 3,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_08.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 3,
    price: "$250.00",
  },
  {
    image: "assets/img/shop_09.jpg",
    name: "Oupidatat non",
    sizes: ["M", "L", "X", "XL"],
    colors: ["red", "blue", "black", "light", "green"],
    rating: 3,
    price: "$250.00",
  },
];
