export const EVENT_CREATE_OR_UPDATE = Symbol("EVENT_FORM_CUSTOMERS_CREATE_OR_UPDATE");
export const EVENT_DELETE = Symbol("EVENT_FORM_CUSTOMERS_DELETE");
export const EVENT_CLOSE = Symbol("EVENT_FORM_CUSTOMERS_CLOSE");