name: Build and publish docker AgapeAppSena image
on:
  push:
    branches:
      - main
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v3
        name: Checks-out your repository

      # https://github.com/marketplace/actions/docker-login
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - working-directory: .
        run: |
          docker build . -t mapineda48/agape-app-sena
          docker push mapineda48/agape-app-sena
